import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const result = await build({
  entryPoints: [fileURLToPath(new URL("../src/internal/runtime-entry.ts", import.meta.url))],
  alias: {
    "@gasboost/client": fileURLToPath(new URL("../../client/src/index.ts", import.meta.url)),
  },
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  write: false,
});

const generated = new URL("../src/generated/", import.meta.url);
await mkdir(generated, { recursive: true });
await writeFile(
  new URL("runtime-bundle.ts", generated),
  `// Generated by scripts/build-runtime.mjs.\nexport const APPS_SCRIPT_BRIDGE_RUNTIME_BUNDLE = ${JSON.stringify(result.outputFiles[0].text)};\n`,
);
